services:
  back:
    build: ./
    container_name: pc_make_app
    volumes:
      - .:/app
    ports:
      - 8880:8000
  
  db:
    image: mysql:8.0
    container_name: pc_make_db
    volumes:
      - make_pc_mysql:/var/lib/mysql
    ports:
      - 33306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  make_pc_mysql:
